23_[BE]_Check In and Out Functionality
albetz99/online_attendance_system pull request #18
Opened 2020-10-30 17:22 UTC by stevenwijaya2

Check In and Out Functionality (tap in , out , 2x tap out in 1 day handler)
Dynamic button tap in name based on DB Status (already tap in or not)
Create CheckIn Model,View and Controller
Implementing CSRF for security reason in login and checkin form
Changing App TimeZone to Asia/Bangkok
set message for every action on clicked tap in button (not so important)

2020-10-31 14:08 UTC, nandaputriafifah commented on app/Views/pages/Home.php
> +        //     var today = new Date();
ini bakal dipake lagi gak? kalo gak, apus aja wkwk

2020-10-31 14:10 UTC, nandaputriafifah commented on app/Views/pages/Home.php
> +            $('#currentTime').html(currTime);
ini `var currTime`-nya kan di comment, nah terus buat jalanin ini `currTime`nya dapet darimana value nya?

2020-10-31 14:13 UTC, nandaputriafifah commented on app/Views/pages/Home.php
> +            // if( currTime <= '8:30' ){
kan masuknya jam 7.30 pen?

2020-10-31 14:14 UTC, nandaputriafifah requested changes
some comments

2020-10-31 14:18 UTC, stevenwijaya2 commented on app/Views/pages/Home.php
> +            // if( currTime <= '8:30' ){
Buat sekarang berarti button masih ke disable, makanya gua lagi nanya rules di grup

2020-10-31 14:19 UTC, stevenwijaya2 commented on app/Views/pages/Home.php
> +            $('#currentTime').html(currTime);
Pake salah satu aja , mau tembak sendiri (buat testing) atau mau pake waktu saat ini (real)

2020-10-31 14:20 UTC, stevenwijaya2 commented on app/Views/pages/Home.php
> +        //     var today = new Date();
Sip tar gua apus

2020-11-01 05:11 UTC, nandaputriafifah approved these changes
Lgtm👍👍👍

2020-11-01 13:47 UTC, merged